# Generated by Django 3.0.5 on 2020-05-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Orange', 'Orange'), ('Green', 'Green')], default='White', max_length=10),
        ),
    ]
