# Generated by Django 3.0.5 on 2020-05-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_bagitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
