# Generated by Django 3.0.5 on 2020-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200529_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image2',
            field=models.ImageField(default='default-product.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image3',
            field=models.ImageField(default='default-product.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image4',
            field=models.ImageField(default='default-product.jpg', upload_to='products'),
        ),
    ]
