# Generated by Django 2.1.1 on 2020-07-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_wishlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlists',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
